---
  tasks:
    - name: HelloTask
      queue: hello_task
      import: demo_worker.tasks
      max_retry: 0

    - name: TravisActiveRepos
      queue: travis_active_repos_task
      import: demo_worker.tasks
      max_retry: 0
      storage: Redis

    - name: TravisRepoBuilds
      queue: travis_repo_builds_task
      import: demo_worker.tasks
      max_retry: 0
      storage: Redis

    - name: TravisLogTxt
      queue: travis_log_txt_task
      import: demo_worker.tasks
      max_retry: 0
      storage: Redis

    - name: TravisRepoBuildsCount
      queue: travis_repo_builds_count_task
      import: demo_worker.tasks
      max_retry: 0
      storage: Redis

    - name: TravisLogCleanup
      queue: travis_log_cleanup
      import: demo_worker.tasks
      max_retry: 0
      storage: TravisLogsStorage

  flows:
    - hello
    - _travis_repo_builds
    - travis_repo_logs
    - travis_org_logs
    - travis_build_logs

  storages:
  - name: Memory
    classname: InMemoryStorage
    import: selinon.storages.memory
    configuration:
      echo: false

  - name: Redis
    import: selinon.storages.redis
    configuration:
      host: redis
      port: 6379
      db: 1
      charset: 'utf-8'

  - name: TravisLogsStorage
    import: demo_worker.storages
    configuration:
      bucket: 'travis'
      aws_access_key_id: 'PCOMYKL7WQ8ZCESM0TH9'
      aws_secret_access_key: 'aHDakH5CK/5LPM2kDnQX6BAlp9CyIOI9V3E+aU+S'
      region_name: 'us-east-1'
      location: 'us-east-1'
      endpoint_url: 'http://minio:80'

  global:
    trace:
      - json: true
    migration_dir: demo_worker/migration_dir
